name: Build and test e-shop

on:
  workflow_dispatch:
  push:

jobs:
  Install:
   runs-on: ubuntu-latest

   steps:
    - name: Code checkout
      uses: actions/checkout@v4.1.1
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Setup NodeJS
      uses: actions/setup-node@v4.0.0
      with:
        node-version: 14

    - name: Cache node modules
      uses: actions/cache@v3.3.2
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: node_modules-

    - name: Install packages with npm
      run: |
        npm ci

    
  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}


      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors
        
      - name: Cache node modules and build folder
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os}}--build-${{ github.run_id }}
          restore-keys: ${{ runner.os}}--build-${{ github.run_id }}

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 14

      - name: Cache node modules
        uses: actions/cache@v3.3.2
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}


      - name: Run tests
        run: |
          npm run test -- --colors

  Deploy:
    needs: [Build, Test]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.1.1
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      
      - name: Load Node modules and build folder
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./build
          key: ${{ runner.os}}--build-${{ github.run_id }}

      # - name: Deploy to Firebase
      #  uses: lowply/deploy-firebase@v0.0.5
      #  env:
      #    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #    FIREBASE_PROJECT: zaloudek-devops
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: |
          source /opt/pipx/venvs/ansible-core/bin/activate
          python -m pip install boto3 botocore

      - name: Ansible pplaybook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ec2_deploy.yml
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          options: |
            --user ec2-user
            --extra-vars "access_key=${{ secrets.AWS_ACCESS_KEY }} secret_key=${{ secrets.AWS_SECRET_KEY }} session_token=${{ secrets.AWS_SESSION_TOKEN }}"

